# Generated by Django 6.0.4 on 2026-04-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothers_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('women', 'Женщинам'), ('men', 'Мужчинам'), ('kids', 'Детям'), ('all', 'Всем')], default='all', max_length=10, verbose_name='Раздел'),
        ),
    ]
